[dev]
	db = "db1"
	host = "host1"
	port = 1
	db_name="dbname1"
	user="user1"
	pass="pass1"
	ssl_mode="sslmode1"
	blacklist=["blacklist1"]
	whitelist=["whitelist1"]
	tag=["tag1"]
	base_dir="basedir1"
	output="output1"
	pkg_name="pkgname1"
	schema="schema1"
	tinyint_not_bool=true
	no_auto_timestamps=true
	debug=true
	no_hooks=true
	no_tests=true
[prod]
	db = "db2"
	host = "host2"
	port = 2
	db_name="dbname2"
	user="user2"
	pass="pass2"
	ssl_mode="sslmode2"
	blacklist=["blacklist2"]
	whitelist=["whitelist2"]
	tag=["tag2"]
	base_dir="basedir2"
	output="output2"
	pkg_name="pkgname2"
	schema="schema2"
	tinyint_not_bool=true
	no_auto_timestamps=true
	debug=true
	no_hooks=true
	no_tests=true
